version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - durationcheck
    - errorlint
    - exhaustive
    - forbidigo
    - gochecknoinits
    - goconst
    - gocritic
    - godot
    - gomoddirectives
    - goprintffuncname
    - gosec
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - predeclared
    - revive
    - tparallel
    - unconvert
    - usestdlibvars
    - whitespace
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    gocritic:
      settings:
        underef:
          skipRecvDeref: false
    govet:
      enable-all: true
      disable:
        - fieldalignment
        - shadow
    nakedret:
      max-func-lines: 0
    nolintlint:
      allow-no-explanation: [forbidigo, tracecheck, gomnd, gochecknoinits, makezero]
      require-explanation: true
      require-specific: true
    revive:
      severity: error
      rules:
        - name: atomic
        - name: line-length-limit
          arguments: [200]
        - name: unhandled-error
          arguments:
            - fmt.Printf
            - fmt.Println
            - fmt.Fprintf
            - fmt.Fprintln
            - os.Stderr.Sync
            - sb.WriteString
            - buf.WriteString
            - hasher.Write
            - os.Setenv
            - os.RemoveAll
        - name: var-naming
          arguments: [["ID", "URL", "HTTP", "API"], []]

formatters:
  enable:
    - goimports

issues:
  max-same-issues: 50
