version: 2
project_name: cone
builds:
  - binary: cone
    env:
      - CGO_ENABLED=0
    id: linux
    main: ./cmd/cone
    goos:
      - linux
    goarch:
      - amd64
      - arm64
  - binary: cone
    env:
      - CGO_ENABLED=0
    id: windows
    main: ./cmd/cone
    goos:
      - windows
    goarch:
      - amd64
  - binary: cone
    env:
      - CGO_ENABLED=0
    id: macos-amd64
    main: ./cmd/cone
    goos:
      - darwin
    goarch:
      - amd64
    hooks:
      post:
        - gon .gon-amd64.json
        - mv dist/cone-darwin-amd64.signed.zip dist/macos-amd64_darwin_amd64_v1/cone
  - binary: cone
    env:
      - CGO_ENABLED=0
    id: macos-arm64
    main: ./cmd/cone
    goos:
      - darwin
    goarch:
      - arm64
    hooks:
      post:
        - gon .gon-arm64.json
        - mv dist/cone-darwin-arm64.signed.zip dist/macos-arm64_darwin_arm64/cone
archives:
  - id: linux-archive
    builds:
      - linux
    format: tar.gz
    name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    files:
      - none*
  - id: windows-archive
    builds:
      - windows
    format: zip
    name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    files:
      - none*
  - id: darwin-archive
    builds:
      - macos-amd64
      - macos-arm64
    format: binary
    name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}.zip"
    files:
      - none*
release:
  ids:
    - linux-archive
    - darwin-archive
    - windows-archive
snapshot:
  version_template: '{{ incpatch .Version }}-dev'
checksum:
  ids:
    - linux-archive
    - windows-archive
  extra_files:
    - glob: ./dist/*-darwin-amd64.zip
    - glob: ./dist/*-darwin-arm64.zip
brews:
  - name: homebrew-cone
    homepage: https://conductorone.com
    test: |
      system "#{bin}/cone -v"
    install: |-
      bin.install "cone"

changelog:
  filters:
    exclude:
      - '^docs:'
      - typo
      - lint
      - Merge pull request