/*
ConductorOne API

Testing AppEntitlementUserBindingAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package c1api

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/conductorone/cone/internal/c1api"
)

func Test_c1api_AppEntitlementUserBindingAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AppEntitlementUserBindingAPIService C1ApiAppV1AppEntitlementUserBindingServiceListAppUsersForIdentityWithGrant", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var appId string
		var appEntitlementId string
		var identityUserId string

		resp, httpRes, err := apiClient.AppEntitlementUserBindingAPI.C1ApiAppV1AppEntitlementUserBindingServiceListAppUsersForIdentityWithGrant(context.Background(), appId, appEntitlementId, identityUserId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
