package scaffold

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func TestGenerate(t *testing.T) {
	// Create temp directory
	tmpDir := t.TempDir()

	outputDir := filepath.Join(tmpDir, "baton-test-app")

	cfg := &Config{
		Name:        "test-app",
		ModulePath:  "github.com/example/baton-test-app",
		OutputDir:   outputDir,
		Description: "Test connector for testing",
	}

	if err := Generate(cfg); err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	// Verify expected files exist
	// These match the files generated by scaffold.Generate
	// Note: connectors sync three fundamental resource types:
	// - users (principals that receive grants)
	// - groups (with "member" entitlement)
	// - roles (with "assigned" entitlement)
	expectedFiles := []string{
		"go.mod",
		"main.go",
		"pkg/connector/connector.go",
		"pkg/connector/resource_types.go",
		"pkg/connector/users.go",
		"pkg/connector/groups.go",
		"pkg/connector/roles.go",
		"pkg/connector/actions.go",
		"pkg/client/client.go",
		"docs/README.md",
		"docs/API_NOTES.md",
		"docs/.gitignore",
		".gitignore",
		".golangci.yml",
		".github/workflows/ci.yaml",
		".github/workflows/release.yaml",
		"README.md",
		"Makefile",
		"CLAUDE.md",
		"Dockerfile",
		"Dockerfile.lambda",
		"docker-compose.yml",
	}

	for _, f := range expectedFiles {
		path := filepath.Join(outputDir, f)
		if _, err := os.Stat(path); os.IsNotExist(err) {
			t.Errorf("expected file %s to exist", f)
		}
	}

	// Verify go.mod contains module path
	goMod, err := os.ReadFile(filepath.Join(outputDir, "go.mod"))
	if err != nil {
		t.Fatalf("failed to read go.mod: %v", err)
	}
	if !strings.Contains(string(goMod), "github.com/example/baton-test-app") {
		t.Error("go.mod should contain module path")
	}

	// Verify main.go contains connector name
	mainGo, err := os.ReadFile(filepath.Join(outputDir, "main.go"))
	if err != nil {
		t.Fatalf("failed to read main.go: %v", err)
	}
	if !strings.Contains(string(mainGo), "baton-test-app") {
		t.Error("main.go should contain connector name")
	}
}

func TestGenerateDefaults(t *testing.T) {
	tmpDir := t.TempDir()

	// Change to temp dir so default output dir works
	t.Chdir(tmpDir)

	cfg := &Config{
		Name: "my-service",
	}

	if err := Generate(cfg); err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	// Verify defaults were applied
	expectedDir := filepath.Join(tmpDir, "baton-my-service")
	if _, err := os.Stat(expectedDir); os.IsNotExist(err) {
		t.Error("expected default output directory baton-my-service")
	}

	// Verify default module path
	goMod, err := os.ReadFile(filepath.Join(expectedDir, "go.mod"))
	if err != nil {
		t.Fatalf("failed to read go.mod: %v", err)
	}
	if !strings.Contains(string(goMod), "github.com/conductorone/baton-my-service") {
		t.Error("go.mod should contain default module path")
	}
}

func TestGenerateMissingName(t *testing.T) {
	cfg := &Config{}

	err := Generate(cfg)
	if err == nil {
		t.Error("expected error for missing name")
	}
}

func TestToPascalCase(t *testing.T) {
	tests := []struct {
		input    string
		expected string
	}{
		{"my-app", "MyApp"},
		{"test", "Test"},
		{"foo-bar-baz", "FooBarBaz"},
		{"", ""},
	}

	for _, tc := range tests {
		result := toPascalCase(tc.input)
		if result != tc.expected {
			t.Errorf("toPascalCase(%q) = %q, expected %q", tc.input, result, tc.expected)
		}
	}
}

// TestGenerateCompiles verifies that generated code actually compiles.
// This is a CRITICAL test - without it, templates can drift from working code
// and remain broken silently. This catches SDK API changes, import errors, etc.
//
// This test requires network access for go mod download.
// Set SKIP_COMPILE_TEST=1 to skip in offline CI environments.
func TestGenerateCompiles(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping compilation test in short mode")
	}

	if os.Getenv("SKIP_COMPILE_TEST") != "" {
		t.Skip("skipping compilation test: SKIP_COMPILE_TEST is set")
	}

	tmpDir := t.TempDir()

	outputDir := filepath.Join(tmpDir, "baton-compile-test")

	cfg := &Config{
		Name:        "compile-test",
		ModulePath:  "github.com/example/baton-compile-test",
		OutputDir:   outputDir,
		Description: "Test connector to verify compilation",
	}

	if err := Generate(cfg); err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	// Run go mod tidy to download dependencies
	runCommand(t, outputDir, 5*time.Minute, "go", "mod", "tidy")

	// Run go build to verify compilation
	runCommand(t, outputDir, 3*time.Minute, "go", "build", "-o", "/dev/null", ".")

	t.Log("Generated code compiles successfully")
}

// TestGenerateVet runs go vet on generated code.
// This catches common issues like unreachable code, shadow variables, etc.
func TestGenerateVet(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping vet test in short mode")
	}

	if os.Getenv("SKIP_COMPILE_TEST") != "" {
		t.Skip("skipping vet test: SKIP_COMPILE_TEST is set")
	}

	tmpDir := t.TempDir()

	outputDir := filepath.Join(tmpDir, "baton-vet-test")

	cfg := &Config{
		Name:        "vet-test",
		ModulePath:  "github.com/example/baton-vet-test",
		OutputDir:   outputDir,
		Description: "Test connector to verify go vet passes",
	}

	if err := Generate(cfg); err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	// Run go mod tidy first
	runCommand(t, outputDir, 5*time.Minute, "go", "mod", "tidy")

	// Run go vet
	runCommand(t, outputDir, 2*time.Minute, "go", "vet", "./...")

	t.Log("Generated code passes go vet")
}

// runCommand runs a command with timeout and fails the test on error.
func runCommand(t *testing.T, dir string, timeout time.Duration, name string, args ...string) {
	t.Helper()

	ctx, cancel := context.WithTimeout(context.Background(), timeout)
	defer cancel()

	cmd := exec.CommandContext(ctx, name, args...)
	cmd.Dir = dir

	output, err := cmd.CombinedOutput()
	if ctx.Err() == context.DeadlineExceeded {
		t.Fatalf("%s timed out after %v", name, timeout)
	}
	if err != nil {
		t.Fatalf("%s %v failed: %v\nOutput:\n%s", name, args, err, string(output))
	}
}
