/*
ConductorOne API

The ConductorOne API is a HTTP API for managing ConductorOne resources.

API version: 0.1.0-alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package c1api

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


// AppResourceAPIService AppResourceAPI service
type AppResourceAPIService service

type AppResourceAPIC1ApiAppV1AppResourceServiceGetRequest struct {
	ctx context.Context
	ApiService *AppResourceAPIService
	appId string
	appResourceTypeId string
	id string
}

func (r AppResourceAPIC1ApiAppV1AppResourceServiceGetRequest) Execute() (*C1ApiAppV1AppResourceServiceGetResponse, *http.Response, error) {
	return r.ApiService.C1ApiAppV1AppResourceServiceGetExecute(r)
}

/*
C1ApiAppV1AppResourceServiceGet Method for C1ApiAppV1AppResourceServiceGet

Invokes the c1.api.app.v1.AppResourceService.Get method.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param appId
 @param appResourceTypeId
 @param id
 @return AppResourceAPIC1ApiAppV1AppResourceServiceGetRequest
*/
func (a *AppResourceAPIService) C1ApiAppV1AppResourceServiceGet(ctx context.Context, appId string, appResourceTypeId string, id string) AppResourceAPIC1ApiAppV1AppResourceServiceGetRequest {
	return AppResourceAPIC1ApiAppV1AppResourceServiceGetRequest{
		ApiService: a,
		ctx: ctx,
		appId: appId,
		appResourceTypeId: appResourceTypeId,
		id: id,
	}
}

// Execute executes the request
//  @return C1ApiAppV1AppResourceServiceGetResponse
func (a *AppResourceAPIService) C1ApiAppV1AppResourceServiceGetExecute(r AppResourceAPIC1ApiAppV1AppResourceServiceGetRequest) (*C1ApiAppV1AppResourceServiceGetResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *C1ApiAppV1AppResourceServiceGetResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AppResourceAPIService.C1ApiAppV1AppResourceServiceGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/apps/{app_id}/resource_types/{app_resource_type_id}/resources/{id}"
	localVarPath = strings.Replace(localVarPath, "{"+"app_id"+"}", url.PathEscape(parameterValueToString(r.appId, "appId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"app_resource_type_id"+"}", url.PathEscape(parameterValueToString(r.appResourceTypeId, "appResourceTypeId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type AppResourceAPIC1ApiAppV1AppResourceServiceListRequest struct {
	ctx context.Context
	ApiService *AppResourceAPIService
	appId string
	appResourceTypeId string
}

func (r AppResourceAPIC1ApiAppV1AppResourceServiceListRequest) Execute() (*C1ApiAppV1AppResourceServiceListResponse, *http.Response, error) {
	return r.ApiService.C1ApiAppV1AppResourceServiceListExecute(r)
}

/*
C1ApiAppV1AppResourceServiceList Method for C1ApiAppV1AppResourceServiceList

Invokes the c1.api.app.v1.AppResourceService.List method.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param appId
 @param appResourceTypeId
 @return AppResourceAPIC1ApiAppV1AppResourceServiceListRequest
*/
func (a *AppResourceAPIService) C1ApiAppV1AppResourceServiceList(ctx context.Context, appId string, appResourceTypeId string) AppResourceAPIC1ApiAppV1AppResourceServiceListRequest {
	return AppResourceAPIC1ApiAppV1AppResourceServiceListRequest{
		ApiService: a,
		ctx: ctx,
		appId: appId,
		appResourceTypeId: appResourceTypeId,
	}
}

// Execute executes the request
//  @return C1ApiAppV1AppResourceServiceListResponse
func (a *AppResourceAPIService) C1ApiAppV1AppResourceServiceListExecute(r AppResourceAPIC1ApiAppV1AppResourceServiceListRequest) (*C1ApiAppV1AppResourceServiceListResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *C1ApiAppV1AppResourceServiceListResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AppResourceAPIService.C1ApiAppV1AppResourceServiceList")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/apps/{app_id}/resource_types/{app_resource_type_id}/resources"
	localVarPath = strings.Replace(localVarPath, "{"+"app_id"+"}", url.PathEscape(parameterValueToString(r.appId, "appId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"app_resource_type_id"+"}", url.PathEscape(parameterValueToString(r.appResourceTypeId, "appResourceTypeId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
