/*
ConductorOne API

The ConductorOne API is a HTTP API for managing ConductorOne resources.

API version: 0.1.0-alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package c1api

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


// AppEntitlementUserBindingAPIService AppEntitlementUserBindingAPI service
type AppEntitlementUserBindingAPIService service

type AppEntitlementUserBindingAPIC1ApiAppV1AppEntitlementUserBindingServiceListAppUsersForIdentityWithGrantRequest struct {
	ctx context.Context
	ApiService *AppEntitlementUserBindingAPIService
	appId string
	appEntitlementId string
	identityUserId string
}

func (r AppEntitlementUserBindingAPIC1ApiAppV1AppEntitlementUserBindingServiceListAppUsersForIdentityWithGrantRequest) Execute() (*C1ApiAppV1ListAppUsersForIdentityWithGrantResponse, *http.Response, error) {
	return r.ApiService.C1ApiAppV1AppEntitlementUserBindingServiceListAppUsersForIdentityWithGrantExecute(r)
}

/*
C1ApiAppV1AppEntitlementUserBindingServiceListAppUsersForIdentityWithGrant Method for C1ApiAppV1AppEntitlementUserBindingServiceListAppUsersForIdentityWithGrant

Invokes the c1.api.app.v1.AppEntitlementUserBindingService.ListAppUsersForIdentityWithGrant method.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param appId
 @param appEntitlementId
 @param identityUserId
 @return AppEntitlementUserBindingAPIC1ApiAppV1AppEntitlementUserBindingServiceListAppUsersForIdentityWithGrantRequest
*/
func (a *AppEntitlementUserBindingAPIService) C1ApiAppV1AppEntitlementUserBindingServiceListAppUsersForIdentityWithGrant(ctx context.Context, appId string, appEntitlementId string, identityUserId string) AppEntitlementUserBindingAPIC1ApiAppV1AppEntitlementUserBindingServiceListAppUsersForIdentityWithGrantRequest {
	return AppEntitlementUserBindingAPIC1ApiAppV1AppEntitlementUserBindingServiceListAppUsersForIdentityWithGrantRequest{
		ApiService: a,
		ctx: ctx,
		appId: appId,
		appEntitlementId: appEntitlementId,
		identityUserId: identityUserId,
	}
}

// Execute executes the request
//  @return C1ApiAppV1ListAppUsersForIdentityWithGrantResponse
func (a *AppEntitlementUserBindingAPIService) C1ApiAppV1AppEntitlementUserBindingServiceListAppUsersForIdentityWithGrantExecute(r AppEntitlementUserBindingAPIC1ApiAppV1AppEntitlementUserBindingServiceListAppUsersForIdentityWithGrantRequest) (*C1ApiAppV1ListAppUsersForIdentityWithGrantResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *C1ApiAppV1ListAppUsersForIdentityWithGrantResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AppEntitlementUserBindingAPIService.C1ApiAppV1AppEntitlementUserBindingServiceListAppUsersForIdentityWithGrant")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/apps/{app_id}/entitlements/{app_entitlement_id}/users/{identity_user_id}/grants"
	localVarPath = strings.Replace(localVarPath, "{"+"app_id"+"}", url.PathEscape(parameterValueToString(r.appId, "appId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"app_entitlement_id"+"}", url.PathEscape(parameterValueToString(r.appEntitlementId, "appEntitlementId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"identity_user_id"+"}", url.PathEscape(parameterValueToString(r.identityUserId, "identityUserId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
