/*
ConductorOne API

The ConductorOne API is a HTTP API for managing ConductorOne resources.

API version: 0.1.0-alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package c1api

import (
	"encoding/json"
)

// checks if the C1ApiUserV1UserServiceListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &C1ApiUserV1UserServiceListResponse{}

// C1ApiUserV1UserServiceListResponse The UserServiceListResponse message.
type C1ApiUserV1UserServiceListResponse struct {
	// The expanded field.
	Expanded []C1ApiAppV1AppResourceServiceGetResponseExpandedInner `json:"expanded,omitempty"`
	// The list field.
	List []C1ApiUserV1UserView `json:"list,omitempty"`
	// The nextPageToken field.
	NextPageToken *string `json:"nextPageToken,omitempty"`
	// The notificationToken field.
	NotificationToken *string `json:"notificationToken,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _C1ApiUserV1UserServiceListResponse C1ApiUserV1UserServiceListResponse

// NewC1ApiUserV1UserServiceListResponse instantiates a new C1ApiUserV1UserServiceListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewC1ApiUserV1UserServiceListResponse() *C1ApiUserV1UserServiceListResponse {
	this := C1ApiUserV1UserServiceListResponse{}
	return &this
}

// NewC1ApiUserV1UserServiceListResponseWithDefaults instantiates a new C1ApiUserV1UserServiceListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewC1ApiUserV1UserServiceListResponseWithDefaults() *C1ApiUserV1UserServiceListResponse {
	this := C1ApiUserV1UserServiceListResponse{}
	return &this
}

// GetExpanded returns the Expanded field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *C1ApiUserV1UserServiceListResponse) GetExpanded() []C1ApiAppV1AppResourceServiceGetResponseExpandedInner {
	if o == nil {
		var ret []C1ApiAppV1AppResourceServiceGetResponseExpandedInner
		return ret
	}
	return o.Expanded
}

// GetExpandedOk returns a tuple with the Expanded field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *C1ApiUserV1UserServiceListResponse) GetExpandedOk() ([]C1ApiAppV1AppResourceServiceGetResponseExpandedInner, bool) {
	if o == nil || IsNil(o.Expanded) {
		return nil, false
	}
	return o.Expanded, true
}

// HasExpanded returns a boolean if a field has been set.
func (o *C1ApiUserV1UserServiceListResponse) HasExpanded() bool {
	if o != nil && IsNil(o.Expanded) {
		return true
	}

	return false
}

// SetExpanded gets a reference to the given []C1ApiAppV1AppResourceServiceGetResponseExpandedInner and assigns it to the Expanded field.
func (o *C1ApiUserV1UserServiceListResponse) SetExpanded(v []C1ApiAppV1AppResourceServiceGetResponseExpandedInner) {
	o.Expanded = v
}

// GetList returns the List field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *C1ApiUserV1UserServiceListResponse) GetList() []C1ApiUserV1UserView {
	if o == nil {
		var ret []C1ApiUserV1UserView
		return ret
	}
	return o.List
}

// GetListOk returns a tuple with the List field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *C1ApiUserV1UserServiceListResponse) GetListOk() ([]C1ApiUserV1UserView, bool) {
	if o == nil || IsNil(o.List) {
		return nil, false
	}
	return o.List, true
}

// HasList returns a boolean if a field has been set.
func (o *C1ApiUserV1UserServiceListResponse) HasList() bool {
	if o != nil && IsNil(o.List) {
		return true
	}

	return false
}

// SetList gets a reference to the given []C1ApiUserV1UserView and assigns it to the List field.
func (o *C1ApiUserV1UserServiceListResponse) SetList(v []C1ApiUserV1UserView) {
	o.List = v
}

// GetNextPageToken returns the NextPageToken field value if set, zero value otherwise.
func (o *C1ApiUserV1UserServiceListResponse) GetNextPageToken() string {
	if o == nil || IsNil(o.NextPageToken) {
		var ret string
		return ret
	}
	return *o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *C1ApiUserV1UserServiceListResponse) GetNextPageTokenOk() (*string, bool) {
	if o == nil || IsNil(o.NextPageToken) {
		return nil, false
	}
	return o.NextPageToken, true
}

// HasNextPageToken returns a boolean if a field has been set.
func (o *C1ApiUserV1UserServiceListResponse) HasNextPageToken() bool {
	if o != nil && !IsNil(o.NextPageToken) {
		return true
	}

	return false
}

// SetNextPageToken gets a reference to the given string and assigns it to the NextPageToken field.
func (o *C1ApiUserV1UserServiceListResponse) SetNextPageToken(v string) {
	o.NextPageToken = &v
}

// GetNotificationToken returns the NotificationToken field value if set, zero value otherwise.
func (o *C1ApiUserV1UserServiceListResponse) GetNotificationToken() string {
	if o == nil || IsNil(o.NotificationToken) {
		var ret string
		return ret
	}
	return *o.NotificationToken
}

// GetNotificationTokenOk returns a tuple with the NotificationToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *C1ApiUserV1UserServiceListResponse) GetNotificationTokenOk() (*string, bool) {
	if o == nil || IsNil(o.NotificationToken) {
		return nil, false
	}
	return o.NotificationToken, true
}

// HasNotificationToken returns a boolean if a field has been set.
func (o *C1ApiUserV1UserServiceListResponse) HasNotificationToken() bool {
	if o != nil && !IsNil(o.NotificationToken) {
		return true
	}

	return false
}

// SetNotificationToken gets a reference to the given string and assigns it to the NotificationToken field.
func (o *C1ApiUserV1UserServiceListResponse) SetNotificationToken(v string) {
	o.NotificationToken = &v
}

func (o C1ApiUserV1UserServiceListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o C1ApiUserV1UserServiceListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Expanded != nil {
		toSerialize["expanded"] = o.Expanded
	}
	if o.List != nil {
		toSerialize["list"] = o.List
	}
	if !IsNil(o.NextPageToken) {
		toSerialize["nextPageToken"] = o.NextPageToken
	}
	if !IsNil(o.NotificationToken) {
		toSerialize["notificationToken"] = o.NotificationToken
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *C1ApiUserV1UserServiceListResponse) UnmarshalJSON(bytes []byte) (err error) {
	varC1ApiUserV1UserServiceListResponse := _C1ApiUserV1UserServiceListResponse{}

	if err = json.Unmarshal(bytes, &varC1ApiUserV1UserServiceListResponse); err == nil {
		*o = C1ApiUserV1UserServiceListResponse(varC1ApiUserV1UserServiceListResponse)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "expanded")
		delete(additionalProperties, "list")
		delete(additionalProperties, "nextPageToken")
		delete(additionalProperties, "notificationToken")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableC1ApiUserV1UserServiceListResponse struct {
	value *C1ApiUserV1UserServiceListResponse
	isSet bool
}

func (v NullableC1ApiUserV1UserServiceListResponse) Get() *C1ApiUserV1UserServiceListResponse {
	return v.value
}

func (v *NullableC1ApiUserV1UserServiceListResponse) Set(val *C1ApiUserV1UserServiceListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableC1ApiUserV1UserServiceListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableC1ApiUserV1UserServiceListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableC1ApiUserV1UserServiceListResponse(val *C1ApiUserV1UserServiceListResponse) *NullableC1ApiUserV1UserServiceListResponse {
	return &NullableC1ApiUserV1UserServiceListResponse{value: val, isSet: true}
}

func (v NullableC1ApiUserV1UserServiceListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableC1ApiUserV1UserServiceListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


