/*
ConductorOne API

The ConductorOne API is a HTTP API for managing ConductorOne resources.

API version: 0.1.0-alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package c1api

import (
	"encoding/json"
)

// checks if the C1ApiPolicyV1DelegatedProvision type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &C1ApiPolicyV1DelegatedProvision{}

// C1ApiPolicyV1DelegatedProvision The DelegatedProvision message.
type C1ApiPolicyV1DelegatedProvision struct {
	// The appId field.
	AppId interface{} `json:"appId,omitempty"`
	// The entitlementId field.
	EntitlementId interface{} `json:"entitlementId,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _C1ApiPolicyV1DelegatedProvision C1ApiPolicyV1DelegatedProvision

// NewC1ApiPolicyV1DelegatedProvision instantiates a new C1ApiPolicyV1DelegatedProvision object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewC1ApiPolicyV1DelegatedProvision() *C1ApiPolicyV1DelegatedProvision {
	this := C1ApiPolicyV1DelegatedProvision{}
	return &this
}

// NewC1ApiPolicyV1DelegatedProvisionWithDefaults instantiates a new C1ApiPolicyV1DelegatedProvision object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewC1ApiPolicyV1DelegatedProvisionWithDefaults() *C1ApiPolicyV1DelegatedProvision {
	this := C1ApiPolicyV1DelegatedProvision{}
	return &this
}

// GetAppId returns the AppId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *C1ApiPolicyV1DelegatedProvision) GetAppId() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.AppId
}

// GetAppIdOk returns a tuple with the AppId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *C1ApiPolicyV1DelegatedProvision) GetAppIdOk() (*interface{}, bool) {
	if o == nil || IsNil(o.AppId) {
		return nil, false
	}
	return &o.AppId, true
}

// HasAppId returns a boolean if a field has been set.
func (o *C1ApiPolicyV1DelegatedProvision) HasAppId() bool {
	if o != nil && IsNil(o.AppId) {
		return true
	}

	return false
}

// SetAppId gets a reference to the given interface{} and assigns it to the AppId field.
func (o *C1ApiPolicyV1DelegatedProvision) SetAppId(v interface{}) {
	o.AppId = v
}

// GetEntitlementId returns the EntitlementId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *C1ApiPolicyV1DelegatedProvision) GetEntitlementId() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.EntitlementId
}

// GetEntitlementIdOk returns a tuple with the EntitlementId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *C1ApiPolicyV1DelegatedProvision) GetEntitlementIdOk() (*interface{}, bool) {
	if o == nil || IsNil(o.EntitlementId) {
		return nil, false
	}
	return &o.EntitlementId, true
}

// HasEntitlementId returns a boolean if a field has been set.
func (o *C1ApiPolicyV1DelegatedProvision) HasEntitlementId() bool {
	if o != nil && IsNil(o.EntitlementId) {
		return true
	}

	return false
}

// SetEntitlementId gets a reference to the given interface{} and assigns it to the EntitlementId field.
func (o *C1ApiPolicyV1DelegatedProvision) SetEntitlementId(v interface{}) {
	o.EntitlementId = v
}

func (o C1ApiPolicyV1DelegatedProvision) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o C1ApiPolicyV1DelegatedProvision) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.AppId != nil {
		toSerialize["appId"] = o.AppId
	}
	if o.EntitlementId != nil {
		toSerialize["entitlementId"] = o.EntitlementId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *C1ApiPolicyV1DelegatedProvision) UnmarshalJSON(bytes []byte) (err error) {
	varC1ApiPolicyV1DelegatedProvision := _C1ApiPolicyV1DelegatedProvision{}

	if err = json.Unmarshal(bytes, &varC1ApiPolicyV1DelegatedProvision); err == nil {
		*o = C1ApiPolicyV1DelegatedProvision(varC1ApiPolicyV1DelegatedProvision)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "appId")
		delete(additionalProperties, "entitlementId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableC1ApiPolicyV1DelegatedProvision struct {
	value *C1ApiPolicyV1DelegatedProvision
	isSet bool
}

func (v NullableC1ApiPolicyV1DelegatedProvision) Get() *C1ApiPolicyV1DelegatedProvision {
	return v.value
}

func (v *NullableC1ApiPolicyV1DelegatedProvision) Set(val *C1ApiPolicyV1DelegatedProvision) {
	v.value = val
	v.isSet = true
}

func (v NullableC1ApiPolicyV1DelegatedProvision) IsSet() bool {
	return v.isSet
}

func (v *NullableC1ApiPolicyV1DelegatedProvision) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableC1ApiPolicyV1DelegatedProvision(val *C1ApiPolicyV1DelegatedProvision) *NullableC1ApiPolicyV1DelegatedProvision {
	return &NullableC1ApiPolicyV1DelegatedProvision{value: val, isSet: true}
}

func (v NullableC1ApiPolicyV1DelegatedProvision) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableC1ApiPolicyV1DelegatedProvision) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


