/*
ConductorOne API

The ConductorOne API is a HTTP API for managing ConductorOne resources.

API version: 0.1.0-alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package c1api

import (
	"encoding/json"
)

// checks if the C1ApiAppV1ListAppsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &C1ApiAppV1ListAppsResponse{}

// C1ApiAppV1ListAppsResponse The ListAppsResponse message.
type C1ApiAppV1ListAppsResponse struct {
	// The list field.
	List []C1ApiAppV1App `json:"list,omitempty"`
	// The nextPageToken field.
	NextPageToken *string `json:"nextPageToken,omitempty"`
	// The notificationToken field.
	NotificationToken *string `json:"notificationToken,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _C1ApiAppV1ListAppsResponse C1ApiAppV1ListAppsResponse

// NewC1ApiAppV1ListAppsResponse instantiates a new C1ApiAppV1ListAppsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewC1ApiAppV1ListAppsResponse() *C1ApiAppV1ListAppsResponse {
	this := C1ApiAppV1ListAppsResponse{}
	return &this
}

// NewC1ApiAppV1ListAppsResponseWithDefaults instantiates a new C1ApiAppV1ListAppsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewC1ApiAppV1ListAppsResponseWithDefaults() *C1ApiAppV1ListAppsResponse {
	this := C1ApiAppV1ListAppsResponse{}
	return &this
}

// GetList returns the List field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *C1ApiAppV1ListAppsResponse) GetList() []C1ApiAppV1App {
	if o == nil {
		var ret []C1ApiAppV1App
		return ret
	}
	return o.List
}

// GetListOk returns a tuple with the List field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *C1ApiAppV1ListAppsResponse) GetListOk() ([]C1ApiAppV1App, bool) {
	if o == nil || IsNil(o.List) {
		return nil, false
	}
	return o.List, true
}

// HasList returns a boolean if a field has been set.
func (o *C1ApiAppV1ListAppsResponse) HasList() bool {
	if o != nil && IsNil(o.List) {
		return true
	}

	return false
}

// SetList gets a reference to the given []C1ApiAppV1App and assigns it to the List field.
func (o *C1ApiAppV1ListAppsResponse) SetList(v []C1ApiAppV1App) {
	o.List = v
}

// GetNextPageToken returns the NextPageToken field value if set, zero value otherwise.
func (o *C1ApiAppV1ListAppsResponse) GetNextPageToken() string {
	if o == nil || IsNil(o.NextPageToken) {
		var ret string
		return ret
	}
	return *o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *C1ApiAppV1ListAppsResponse) GetNextPageTokenOk() (*string, bool) {
	if o == nil || IsNil(o.NextPageToken) {
		return nil, false
	}
	return o.NextPageToken, true
}

// HasNextPageToken returns a boolean if a field has been set.
func (o *C1ApiAppV1ListAppsResponse) HasNextPageToken() bool {
	if o != nil && !IsNil(o.NextPageToken) {
		return true
	}

	return false
}

// SetNextPageToken gets a reference to the given string and assigns it to the NextPageToken field.
func (o *C1ApiAppV1ListAppsResponse) SetNextPageToken(v string) {
	o.NextPageToken = &v
}

// GetNotificationToken returns the NotificationToken field value if set, zero value otherwise.
func (o *C1ApiAppV1ListAppsResponse) GetNotificationToken() string {
	if o == nil || IsNil(o.NotificationToken) {
		var ret string
		return ret
	}
	return *o.NotificationToken
}

// GetNotificationTokenOk returns a tuple with the NotificationToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *C1ApiAppV1ListAppsResponse) GetNotificationTokenOk() (*string, bool) {
	if o == nil || IsNil(o.NotificationToken) {
		return nil, false
	}
	return o.NotificationToken, true
}

// HasNotificationToken returns a boolean if a field has been set.
func (o *C1ApiAppV1ListAppsResponse) HasNotificationToken() bool {
	if o != nil && !IsNil(o.NotificationToken) {
		return true
	}

	return false
}

// SetNotificationToken gets a reference to the given string and assigns it to the NotificationToken field.
func (o *C1ApiAppV1ListAppsResponse) SetNotificationToken(v string) {
	o.NotificationToken = &v
}

func (o C1ApiAppV1ListAppsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o C1ApiAppV1ListAppsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.List != nil {
		toSerialize["list"] = o.List
	}
	if !IsNil(o.NextPageToken) {
		toSerialize["nextPageToken"] = o.NextPageToken
	}
	if !IsNil(o.NotificationToken) {
		toSerialize["notificationToken"] = o.NotificationToken
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *C1ApiAppV1ListAppsResponse) UnmarshalJSON(bytes []byte) (err error) {
	varC1ApiAppV1ListAppsResponse := _C1ApiAppV1ListAppsResponse{}

	if err = json.Unmarshal(bytes, &varC1ApiAppV1ListAppsResponse); err == nil {
		*o = C1ApiAppV1ListAppsResponse(varC1ApiAppV1ListAppsResponse)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "list")
		delete(additionalProperties, "nextPageToken")
		delete(additionalProperties, "notificationToken")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableC1ApiAppV1ListAppsResponse struct {
	value *C1ApiAppV1ListAppsResponse
	isSet bool
}

func (v NullableC1ApiAppV1ListAppsResponse) Get() *C1ApiAppV1ListAppsResponse {
	return v.value
}

func (v *NullableC1ApiAppV1ListAppsResponse) Set(val *C1ApiAppV1ListAppsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableC1ApiAppV1ListAppsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableC1ApiAppV1ListAppsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableC1ApiAppV1ListAppsResponse(val *C1ApiAppV1ListAppsResponse) *NullableC1ApiAppV1ListAppsResponse {
	return &NullableC1ApiAppV1ListAppsResponse{value: val, isSet: true}
}

func (v NullableC1ApiAppV1ListAppsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableC1ApiAppV1ListAppsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


