/*
ConductorOne API

The ConductorOne API is a HTTP API for managing ConductorOne resources.

API version: 0.1.0-alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package c1api

import (
	"encoding/json"
)

// checks if the C1ApiTaskV1TaskServiceCreateRevokeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &C1ApiTaskV1TaskServiceCreateRevokeRequest{}

// C1ApiTaskV1TaskServiceCreateRevokeRequest The TaskServiceCreateRevokeRequest message.
type C1ApiTaskV1TaskServiceCreateRevokeRequest struct {
	// The appEntitlementId field.
	AppEntitlementId *string `json:"appEntitlementId,omitempty"`
	// The appId field.
	AppId *string `json:"appId,omitempty"`
	// The appUserId field.
	AppUserId *string `json:"appUserId,omitempty"`
	// The description field.
	Description *string `json:"description,omitempty"`
	ExpandMask *C1ApiTaskV1TaskExpandMask `json:"expandMask,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _C1ApiTaskV1TaskServiceCreateRevokeRequest C1ApiTaskV1TaskServiceCreateRevokeRequest

// NewC1ApiTaskV1TaskServiceCreateRevokeRequest instantiates a new C1ApiTaskV1TaskServiceCreateRevokeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewC1ApiTaskV1TaskServiceCreateRevokeRequest() *C1ApiTaskV1TaskServiceCreateRevokeRequest {
	this := C1ApiTaskV1TaskServiceCreateRevokeRequest{}
	return &this
}

// NewC1ApiTaskV1TaskServiceCreateRevokeRequestWithDefaults instantiates a new C1ApiTaskV1TaskServiceCreateRevokeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewC1ApiTaskV1TaskServiceCreateRevokeRequestWithDefaults() *C1ApiTaskV1TaskServiceCreateRevokeRequest {
	this := C1ApiTaskV1TaskServiceCreateRevokeRequest{}
	return &this
}

// GetAppEntitlementId returns the AppEntitlementId field value if set, zero value otherwise.
func (o *C1ApiTaskV1TaskServiceCreateRevokeRequest) GetAppEntitlementId() string {
	if o == nil || IsNil(o.AppEntitlementId) {
		var ret string
		return ret
	}
	return *o.AppEntitlementId
}

// GetAppEntitlementIdOk returns a tuple with the AppEntitlementId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *C1ApiTaskV1TaskServiceCreateRevokeRequest) GetAppEntitlementIdOk() (*string, bool) {
	if o == nil || IsNil(o.AppEntitlementId) {
		return nil, false
	}
	return o.AppEntitlementId, true
}

// HasAppEntitlementId returns a boolean if a field has been set.
func (o *C1ApiTaskV1TaskServiceCreateRevokeRequest) HasAppEntitlementId() bool {
	if o != nil && !IsNil(o.AppEntitlementId) {
		return true
	}

	return false
}

// SetAppEntitlementId gets a reference to the given string and assigns it to the AppEntitlementId field.
func (o *C1ApiTaskV1TaskServiceCreateRevokeRequest) SetAppEntitlementId(v string) {
	o.AppEntitlementId = &v
}

// GetAppId returns the AppId field value if set, zero value otherwise.
func (o *C1ApiTaskV1TaskServiceCreateRevokeRequest) GetAppId() string {
	if o == nil || IsNil(o.AppId) {
		var ret string
		return ret
	}
	return *o.AppId
}

// GetAppIdOk returns a tuple with the AppId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *C1ApiTaskV1TaskServiceCreateRevokeRequest) GetAppIdOk() (*string, bool) {
	if o == nil || IsNil(o.AppId) {
		return nil, false
	}
	return o.AppId, true
}

// HasAppId returns a boolean if a field has been set.
func (o *C1ApiTaskV1TaskServiceCreateRevokeRequest) HasAppId() bool {
	if o != nil && !IsNil(o.AppId) {
		return true
	}

	return false
}

// SetAppId gets a reference to the given string and assigns it to the AppId field.
func (o *C1ApiTaskV1TaskServiceCreateRevokeRequest) SetAppId(v string) {
	o.AppId = &v
}

// GetAppUserId returns the AppUserId field value if set, zero value otherwise.
func (o *C1ApiTaskV1TaskServiceCreateRevokeRequest) GetAppUserId() string {
	if o == nil || IsNil(o.AppUserId) {
		var ret string
		return ret
	}
	return *o.AppUserId
}

// GetAppUserIdOk returns a tuple with the AppUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *C1ApiTaskV1TaskServiceCreateRevokeRequest) GetAppUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.AppUserId) {
		return nil, false
	}
	return o.AppUserId, true
}

// HasAppUserId returns a boolean if a field has been set.
func (o *C1ApiTaskV1TaskServiceCreateRevokeRequest) HasAppUserId() bool {
	if o != nil && !IsNil(o.AppUserId) {
		return true
	}

	return false
}

// SetAppUserId gets a reference to the given string and assigns it to the AppUserId field.
func (o *C1ApiTaskV1TaskServiceCreateRevokeRequest) SetAppUserId(v string) {
	o.AppUserId = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *C1ApiTaskV1TaskServiceCreateRevokeRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *C1ApiTaskV1TaskServiceCreateRevokeRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *C1ApiTaskV1TaskServiceCreateRevokeRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *C1ApiTaskV1TaskServiceCreateRevokeRequest) SetDescription(v string) {
	o.Description = &v
}

// GetExpandMask returns the ExpandMask field value if set, zero value otherwise.
func (o *C1ApiTaskV1TaskServiceCreateRevokeRequest) GetExpandMask() C1ApiTaskV1TaskExpandMask {
	if o == nil || IsNil(o.ExpandMask) {
		var ret C1ApiTaskV1TaskExpandMask
		return ret
	}
	return *o.ExpandMask
}

// GetExpandMaskOk returns a tuple with the ExpandMask field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *C1ApiTaskV1TaskServiceCreateRevokeRequest) GetExpandMaskOk() (*C1ApiTaskV1TaskExpandMask, bool) {
	if o == nil || IsNil(o.ExpandMask) {
		return nil, false
	}
	return o.ExpandMask, true
}

// HasExpandMask returns a boolean if a field has been set.
func (o *C1ApiTaskV1TaskServiceCreateRevokeRequest) HasExpandMask() bool {
	if o != nil && !IsNil(o.ExpandMask) {
		return true
	}

	return false
}

// SetExpandMask gets a reference to the given C1ApiTaskV1TaskExpandMask and assigns it to the ExpandMask field.
func (o *C1ApiTaskV1TaskServiceCreateRevokeRequest) SetExpandMask(v C1ApiTaskV1TaskExpandMask) {
	o.ExpandMask = &v
}

func (o C1ApiTaskV1TaskServiceCreateRevokeRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o C1ApiTaskV1TaskServiceCreateRevokeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AppEntitlementId) {
		toSerialize["appEntitlementId"] = o.AppEntitlementId
	}
	if !IsNil(o.AppId) {
		toSerialize["appId"] = o.AppId
	}
	if !IsNil(o.AppUserId) {
		toSerialize["appUserId"] = o.AppUserId
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.ExpandMask) {
		toSerialize["expandMask"] = o.ExpandMask
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *C1ApiTaskV1TaskServiceCreateRevokeRequest) UnmarshalJSON(bytes []byte) (err error) {
	varC1ApiTaskV1TaskServiceCreateRevokeRequest := _C1ApiTaskV1TaskServiceCreateRevokeRequest{}

	if err = json.Unmarshal(bytes, &varC1ApiTaskV1TaskServiceCreateRevokeRequest); err == nil {
		*o = C1ApiTaskV1TaskServiceCreateRevokeRequest(varC1ApiTaskV1TaskServiceCreateRevokeRequest)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "appEntitlementId")
		delete(additionalProperties, "appId")
		delete(additionalProperties, "appUserId")
		delete(additionalProperties, "description")
		delete(additionalProperties, "expandMask")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableC1ApiTaskV1TaskServiceCreateRevokeRequest struct {
	value *C1ApiTaskV1TaskServiceCreateRevokeRequest
	isSet bool
}

func (v NullableC1ApiTaskV1TaskServiceCreateRevokeRequest) Get() *C1ApiTaskV1TaskServiceCreateRevokeRequest {
	return v.value
}

func (v *NullableC1ApiTaskV1TaskServiceCreateRevokeRequest) Set(val *C1ApiTaskV1TaskServiceCreateRevokeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableC1ApiTaskV1TaskServiceCreateRevokeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableC1ApiTaskV1TaskServiceCreateRevokeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableC1ApiTaskV1TaskServiceCreateRevokeRequest(val *C1ApiTaskV1TaskServiceCreateRevokeRequest) *NullableC1ApiTaskV1TaskServiceCreateRevokeRequest {
	return &NullableC1ApiTaskV1TaskServiceCreateRevokeRequest{value: val, isSet: true}
}

func (v NullableC1ApiTaskV1TaskServiceCreateRevokeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableC1ApiTaskV1TaskServiceCreateRevokeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


