/*
ConductorOne API

The ConductorOne API is a HTTP API for managing ConductorOne resources.

API version: 0.1.0-alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package c1api

import (
	"encoding/json"
)

// checks if the C1ApiAppV1AppResourceServiceGetResponseExpandedInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &C1ApiAppV1AppResourceServiceGetResponseExpandedInner{}

// C1ApiAppV1AppResourceServiceGetResponseExpandedInner Contains an arbitrary serialized message along with a @type that describes the type of the serialized message.
type C1ApiAppV1AppResourceServiceGetResponseExpandedInner struct {
	// The type of the serialized message.
	Type *string `json:"@type,omitempty"`
}

// NewC1ApiAppV1AppResourceServiceGetResponseExpandedInner instantiates a new C1ApiAppV1AppResourceServiceGetResponseExpandedInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewC1ApiAppV1AppResourceServiceGetResponseExpandedInner() *C1ApiAppV1AppResourceServiceGetResponseExpandedInner {
	this := C1ApiAppV1AppResourceServiceGetResponseExpandedInner{}
	return &this
}

// NewC1ApiAppV1AppResourceServiceGetResponseExpandedInnerWithDefaults instantiates a new C1ApiAppV1AppResourceServiceGetResponseExpandedInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewC1ApiAppV1AppResourceServiceGetResponseExpandedInnerWithDefaults() *C1ApiAppV1AppResourceServiceGetResponseExpandedInner {
	this := C1ApiAppV1AppResourceServiceGetResponseExpandedInner{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *C1ApiAppV1AppResourceServiceGetResponseExpandedInner) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *C1ApiAppV1AppResourceServiceGetResponseExpandedInner) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *C1ApiAppV1AppResourceServiceGetResponseExpandedInner) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *C1ApiAppV1AppResourceServiceGetResponseExpandedInner) SetType(v string) {
	o.Type = &v
}

func (o C1ApiAppV1AppResourceServiceGetResponseExpandedInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o C1ApiAppV1AppResourceServiceGetResponseExpandedInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["@type"] = o.Type
	}
	return toSerialize, nil
}

type NullableC1ApiAppV1AppResourceServiceGetResponseExpandedInner struct {
	value *C1ApiAppV1AppResourceServiceGetResponseExpandedInner
	isSet bool
}

func (v NullableC1ApiAppV1AppResourceServiceGetResponseExpandedInner) Get() *C1ApiAppV1AppResourceServiceGetResponseExpandedInner {
	return v.value
}

func (v *NullableC1ApiAppV1AppResourceServiceGetResponseExpandedInner) Set(val *C1ApiAppV1AppResourceServiceGetResponseExpandedInner) {
	v.value = val
	v.isSet = true
}

func (v NullableC1ApiAppV1AppResourceServiceGetResponseExpandedInner) IsSet() bool {
	return v.isSet
}

func (v *NullableC1ApiAppV1AppResourceServiceGetResponseExpandedInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableC1ApiAppV1AppResourceServiceGetResponseExpandedInner(val *C1ApiAppV1AppResourceServiceGetResponseExpandedInner) *NullableC1ApiAppV1AppResourceServiceGetResponseExpandedInner {
	return &NullableC1ApiAppV1AppResourceServiceGetResponseExpandedInner{value: val, isSet: true}
}

func (v NullableC1ApiAppV1AppResourceServiceGetResponseExpandedInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableC1ApiAppV1AppResourceServiceGetResponseExpandedInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


