/*
ConductorOne API

The ConductorOne API is a HTTP API for managing ConductorOne resources.

API version: 0.1.0-alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package c1api

import (
	"encoding/json"
	"time"
)

// checks if the C1ApiTaskV1TaskRevokeSourceNonUsage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &C1ApiTaskV1TaskRevokeSourceNonUsage{}

// C1ApiTaskV1TaskRevokeSourceNonUsage The TaskRevokeSourceNonUsage message.
type C1ApiTaskV1TaskRevokeSourceNonUsage struct {
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
	LastLogin *time.Time `json:"lastLogin,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _C1ApiTaskV1TaskRevokeSourceNonUsage C1ApiTaskV1TaskRevokeSourceNonUsage

// NewC1ApiTaskV1TaskRevokeSourceNonUsage instantiates a new C1ApiTaskV1TaskRevokeSourceNonUsage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewC1ApiTaskV1TaskRevokeSourceNonUsage() *C1ApiTaskV1TaskRevokeSourceNonUsage {
	this := C1ApiTaskV1TaskRevokeSourceNonUsage{}
	return &this
}

// NewC1ApiTaskV1TaskRevokeSourceNonUsageWithDefaults instantiates a new C1ApiTaskV1TaskRevokeSourceNonUsage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewC1ApiTaskV1TaskRevokeSourceNonUsageWithDefaults() *C1ApiTaskV1TaskRevokeSourceNonUsage {
	this := C1ApiTaskV1TaskRevokeSourceNonUsage{}
	return &this
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise.
func (o *C1ApiTaskV1TaskRevokeSourceNonUsage) GetExpiresAt() time.Time {
	if o == nil || IsNil(o.ExpiresAt) {
		var ret time.Time
		return ret
	}
	return *o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *C1ApiTaskV1TaskRevokeSourceNonUsage) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ExpiresAt) {
		return nil, false
	}
	return o.ExpiresAt, true
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *C1ApiTaskV1TaskRevokeSourceNonUsage) HasExpiresAt() bool {
	if o != nil && !IsNil(o.ExpiresAt) {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given time.Time and assigns it to the ExpiresAt field.
func (o *C1ApiTaskV1TaskRevokeSourceNonUsage) SetExpiresAt(v time.Time) {
	o.ExpiresAt = &v
}

// GetLastLogin returns the LastLogin field value if set, zero value otherwise.
func (o *C1ApiTaskV1TaskRevokeSourceNonUsage) GetLastLogin() time.Time {
	if o == nil || IsNil(o.LastLogin) {
		var ret time.Time
		return ret
	}
	return *o.LastLogin
}

// GetLastLoginOk returns a tuple with the LastLogin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *C1ApiTaskV1TaskRevokeSourceNonUsage) GetLastLoginOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastLogin) {
		return nil, false
	}
	return o.LastLogin, true
}

// HasLastLogin returns a boolean if a field has been set.
func (o *C1ApiTaskV1TaskRevokeSourceNonUsage) HasLastLogin() bool {
	if o != nil && !IsNil(o.LastLogin) {
		return true
	}

	return false
}

// SetLastLogin gets a reference to the given time.Time and assigns it to the LastLogin field.
func (o *C1ApiTaskV1TaskRevokeSourceNonUsage) SetLastLogin(v time.Time) {
	o.LastLogin = &v
}

func (o C1ApiTaskV1TaskRevokeSourceNonUsage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o C1ApiTaskV1TaskRevokeSourceNonUsage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ExpiresAt) {
		toSerialize["expiresAt"] = o.ExpiresAt
	}
	if !IsNil(o.LastLogin) {
		toSerialize["lastLogin"] = o.LastLogin
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *C1ApiTaskV1TaskRevokeSourceNonUsage) UnmarshalJSON(bytes []byte) (err error) {
	varC1ApiTaskV1TaskRevokeSourceNonUsage := _C1ApiTaskV1TaskRevokeSourceNonUsage{}

	if err = json.Unmarshal(bytes, &varC1ApiTaskV1TaskRevokeSourceNonUsage); err == nil {
		*o = C1ApiTaskV1TaskRevokeSourceNonUsage(varC1ApiTaskV1TaskRevokeSourceNonUsage)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "expiresAt")
		delete(additionalProperties, "lastLogin")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableC1ApiTaskV1TaskRevokeSourceNonUsage struct {
	value *C1ApiTaskV1TaskRevokeSourceNonUsage
	isSet bool
}

func (v NullableC1ApiTaskV1TaskRevokeSourceNonUsage) Get() *C1ApiTaskV1TaskRevokeSourceNonUsage {
	return v.value
}

func (v *NullableC1ApiTaskV1TaskRevokeSourceNonUsage) Set(val *C1ApiTaskV1TaskRevokeSourceNonUsage) {
	v.value = val
	v.isSet = true
}

func (v NullableC1ApiTaskV1TaskRevokeSourceNonUsage) IsSet() bool {
	return v.isSet
}

func (v *NullableC1ApiTaskV1TaskRevokeSourceNonUsage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableC1ApiTaskV1TaskRevokeSourceNonUsage(val *C1ApiTaskV1TaskRevokeSourceNonUsage) *NullableC1ApiTaskV1TaskRevokeSourceNonUsage {
	return &NullableC1ApiTaskV1TaskRevokeSourceNonUsage{value: val, isSet: true}
}

func (v NullableC1ApiTaskV1TaskRevokeSourceNonUsage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableC1ApiTaskV1TaskRevokeSourceNonUsage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


