/*
ConductorOne API

The ConductorOne API is a HTTP API for managing ConductorOne resources.

API version: 0.1.0-alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package c1api

import (
	"encoding/json"
	"time"
)

// checks if the C1ApiTaskV1TaskTypeGrant type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &C1ApiTaskV1TaskTypeGrant{}

// C1ApiTaskV1TaskTypeGrant The TaskTypeGrant message.
type C1ApiTaskV1TaskTypeGrant struct {
	// The appEntitlementId field.
	AppEntitlementId *string `json:"appEntitlementId,omitempty"`
	// The appId field.
	AppId *string `json:"appId,omitempty"`
	// The appUserId field.
	AppUserId *string `json:"appUserId,omitempty"`
	GrantDuration *string `json:"grantDuration,omitempty"`
	// The identityUserId field.
	IdentityUserId *string `json:"identityUserId,omitempty"`
	// The outcome field.
	Outcome *string `json:"outcome,omitempty"`
	OutcomeTime *time.Time `json:"outcomeTime,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _C1ApiTaskV1TaskTypeGrant C1ApiTaskV1TaskTypeGrant

// NewC1ApiTaskV1TaskTypeGrant instantiates a new C1ApiTaskV1TaskTypeGrant object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewC1ApiTaskV1TaskTypeGrant() *C1ApiTaskV1TaskTypeGrant {
	this := C1ApiTaskV1TaskTypeGrant{}
	return &this
}

// NewC1ApiTaskV1TaskTypeGrantWithDefaults instantiates a new C1ApiTaskV1TaskTypeGrant object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewC1ApiTaskV1TaskTypeGrantWithDefaults() *C1ApiTaskV1TaskTypeGrant {
	this := C1ApiTaskV1TaskTypeGrant{}
	return &this
}

// GetAppEntitlementId returns the AppEntitlementId field value if set, zero value otherwise.
func (o *C1ApiTaskV1TaskTypeGrant) GetAppEntitlementId() string {
	if o == nil || IsNil(o.AppEntitlementId) {
		var ret string
		return ret
	}
	return *o.AppEntitlementId
}

// GetAppEntitlementIdOk returns a tuple with the AppEntitlementId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *C1ApiTaskV1TaskTypeGrant) GetAppEntitlementIdOk() (*string, bool) {
	if o == nil || IsNil(o.AppEntitlementId) {
		return nil, false
	}
	return o.AppEntitlementId, true
}

// HasAppEntitlementId returns a boolean if a field has been set.
func (o *C1ApiTaskV1TaskTypeGrant) HasAppEntitlementId() bool {
	if o != nil && !IsNil(o.AppEntitlementId) {
		return true
	}

	return false
}

// SetAppEntitlementId gets a reference to the given string and assigns it to the AppEntitlementId field.
func (o *C1ApiTaskV1TaskTypeGrant) SetAppEntitlementId(v string) {
	o.AppEntitlementId = &v
}

// GetAppId returns the AppId field value if set, zero value otherwise.
func (o *C1ApiTaskV1TaskTypeGrant) GetAppId() string {
	if o == nil || IsNil(o.AppId) {
		var ret string
		return ret
	}
	return *o.AppId
}

// GetAppIdOk returns a tuple with the AppId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *C1ApiTaskV1TaskTypeGrant) GetAppIdOk() (*string, bool) {
	if o == nil || IsNil(o.AppId) {
		return nil, false
	}
	return o.AppId, true
}

// HasAppId returns a boolean if a field has been set.
func (o *C1ApiTaskV1TaskTypeGrant) HasAppId() bool {
	if o != nil && !IsNil(o.AppId) {
		return true
	}

	return false
}

// SetAppId gets a reference to the given string and assigns it to the AppId field.
func (o *C1ApiTaskV1TaskTypeGrant) SetAppId(v string) {
	o.AppId = &v
}

// GetAppUserId returns the AppUserId field value if set, zero value otherwise.
func (o *C1ApiTaskV1TaskTypeGrant) GetAppUserId() string {
	if o == nil || IsNil(o.AppUserId) {
		var ret string
		return ret
	}
	return *o.AppUserId
}

// GetAppUserIdOk returns a tuple with the AppUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *C1ApiTaskV1TaskTypeGrant) GetAppUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.AppUserId) {
		return nil, false
	}
	return o.AppUserId, true
}

// HasAppUserId returns a boolean if a field has been set.
func (o *C1ApiTaskV1TaskTypeGrant) HasAppUserId() bool {
	if o != nil && !IsNil(o.AppUserId) {
		return true
	}

	return false
}

// SetAppUserId gets a reference to the given string and assigns it to the AppUserId field.
func (o *C1ApiTaskV1TaskTypeGrant) SetAppUserId(v string) {
	o.AppUserId = &v
}

// GetGrantDuration returns the GrantDuration field value if set, zero value otherwise.
func (o *C1ApiTaskV1TaskTypeGrant) GetGrantDuration() string {
	if o == nil || IsNil(o.GrantDuration) {
		var ret string
		return ret
	}
	return *o.GrantDuration
}

// GetGrantDurationOk returns a tuple with the GrantDuration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *C1ApiTaskV1TaskTypeGrant) GetGrantDurationOk() (*string, bool) {
	if o == nil || IsNil(o.GrantDuration) {
		return nil, false
	}
	return o.GrantDuration, true
}

// HasGrantDuration returns a boolean if a field has been set.
func (o *C1ApiTaskV1TaskTypeGrant) HasGrantDuration() bool {
	if o != nil && !IsNil(o.GrantDuration) {
		return true
	}

	return false
}

// SetGrantDuration gets a reference to the given string and assigns it to the GrantDuration field.
func (o *C1ApiTaskV1TaskTypeGrant) SetGrantDuration(v string) {
	o.GrantDuration = &v
}

// GetIdentityUserId returns the IdentityUserId field value if set, zero value otherwise.
func (o *C1ApiTaskV1TaskTypeGrant) GetIdentityUserId() string {
	if o == nil || IsNil(o.IdentityUserId) {
		var ret string
		return ret
	}
	return *o.IdentityUserId
}

// GetIdentityUserIdOk returns a tuple with the IdentityUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *C1ApiTaskV1TaskTypeGrant) GetIdentityUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.IdentityUserId) {
		return nil, false
	}
	return o.IdentityUserId, true
}

// HasIdentityUserId returns a boolean if a field has been set.
func (o *C1ApiTaskV1TaskTypeGrant) HasIdentityUserId() bool {
	if o != nil && !IsNil(o.IdentityUserId) {
		return true
	}

	return false
}

// SetIdentityUserId gets a reference to the given string and assigns it to the IdentityUserId field.
func (o *C1ApiTaskV1TaskTypeGrant) SetIdentityUserId(v string) {
	o.IdentityUserId = &v
}

// GetOutcome returns the Outcome field value if set, zero value otherwise.
func (o *C1ApiTaskV1TaskTypeGrant) GetOutcome() string {
	if o == nil || IsNil(o.Outcome) {
		var ret string
		return ret
	}
	return *o.Outcome
}

// GetOutcomeOk returns a tuple with the Outcome field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *C1ApiTaskV1TaskTypeGrant) GetOutcomeOk() (*string, bool) {
	if o == nil || IsNil(o.Outcome) {
		return nil, false
	}
	return o.Outcome, true
}

// HasOutcome returns a boolean if a field has been set.
func (o *C1ApiTaskV1TaskTypeGrant) HasOutcome() bool {
	if o != nil && !IsNil(o.Outcome) {
		return true
	}

	return false
}

// SetOutcome gets a reference to the given string and assigns it to the Outcome field.
func (o *C1ApiTaskV1TaskTypeGrant) SetOutcome(v string) {
	o.Outcome = &v
}

// GetOutcomeTime returns the OutcomeTime field value if set, zero value otherwise.
func (o *C1ApiTaskV1TaskTypeGrant) GetOutcomeTime() time.Time {
	if o == nil || IsNil(o.OutcomeTime) {
		var ret time.Time
		return ret
	}
	return *o.OutcomeTime
}

// GetOutcomeTimeOk returns a tuple with the OutcomeTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *C1ApiTaskV1TaskTypeGrant) GetOutcomeTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.OutcomeTime) {
		return nil, false
	}
	return o.OutcomeTime, true
}

// HasOutcomeTime returns a boolean if a field has been set.
func (o *C1ApiTaskV1TaskTypeGrant) HasOutcomeTime() bool {
	if o != nil && !IsNil(o.OutcomeTime) {
		return true
	}

	return false
}

// SetOutcomeTime gets a reference to the given time.Time and assigns it to the OutcomeTime field.
func (o *C1ApiTaskV1TaskTypeGrant) SetOutcomeTime(v time.Time) {
	o.OutcomeTime = &v
}

func (o C1ApiTaskV1TaskTypeGrant) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o C1ApiTaskV1TaskTypeGrant) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AppEntitlementId) {
		toSerialize["appEntitlementId"] = o.AppEntitlementId
	}
	if !IsNil(o.AppId) {
		toSerialize["appId"] = o.AppId
	}
	if !IsNil(o.AppUserId) {
		toSerialize["appUserId"] = o.AppUserId
	}
	if !IsNil(o.GrantDuration) {
		toSerialize["grantDuration"] = o.GrantDuration
	}
	if !IsNil(o.IdentityUserId) {
		toSerialize["identityUserId"] = o.IdentityUserId
	}
	if !IsNil(o.Outcome) {
		toSerialize["outcome"] = o.Outcome
	}
	if !IsNil(o.OutcomeTime) {
		toSerialize["outcomeTime"] = o.OutcomeTime
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *C1ApiTaskV1TaskTypeGrant) UnmarshalJSON(bytes []byte) (err error) {
	varC1ApiTaskV1TaskTypeGrant := _C1ApiTaskV1TaskTypeGrant{}

	if err = json.Unmarshal(bytes, &varC1ApiTaskV1TaskTypeGrant); err == nil {
		*o = C1ApiTaskV1TaskTypeGrant(varC1ApiTaskV1TaskTypeGrant)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "appEntitlementId")
		delete(additionalProperties, "appId")
		delete(additionalProperties, "appUserId")
		delete(additionalProperties, "grantDuration")
		delete(additionalProperties, "identityUserId")
		delete(additionalProperties, "outcome")
		delete(additionalProperties, "outcomeTime")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableC1ApiTaskV1TaskTypeGrant struct {
	value *C1ApiTaskV1TaskTypeGrant
	isSet bool
}

func (v NullableC1ApiTaskV1TaskTypeGrant) Get() *C1ApiTaskV1TaskTypeGrant {
	return v.value
}

func (v *NullableC1ApiTaskV1TaskTypeGrant) Set(val *C1ApiTaskV1TaskTypeGrant) {
	v.value = val
	v.isSet = true
}

func (v NullableC1ApiTaskV1TaskTypeGrant) IsSet() bool {
	return v.isSet
}

func (v *NullableC1ApiTaskV1TaskTypeGrant) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableC1ApiTaskV1TaskTypeGrant(val *C1ApiTaskV1TaskTypeGrant) *NullableC1ApiTaskV1TaskTypeGrant {
	return &NullableC1ApiTaskV1TaskTypeGrant{value: val, isSet: true}
}

func (v NullableC1ApiTaskV1TaskTypeGrant) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableC1ApiTaskV1TaskTypeGrant) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


