/*
ConductorOne API

The ConductorOne API is a HTTP API for managing ConductorOne resources.

API version: 0.1.0-alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package c1api

import (
	"encoding/json"
)

// checks if the C1ApiTaskV1TaskServiceCreateRevokeResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &C1ApiTaskV1TaskServiceCreateRevokeResponse{}

// C1ApiTaskV1TaskServiceCreateRevokeResponse The TaskServiceCreateRevokeResponse message.
type C1ApiTaskV1TaskServiceCreateRevokeResponse struct {
	// The expanded field.
	Expanded []C1ApiAppV1AppResourceServiceGetResponseExpandedInner `json:"expanded,omitempty"`
	TaskView *C1ApiTaskV1TaskView `json:"taskView,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _C1ApiTaskV1TaskServiceCreateRevokeResponse C1ApiTaskV1TaskServiceCreateRevokeResponse

// NewC1ApiTaskV1TaskServiceCreateRevokeResponse instantiates a new C1ApiTaskV1TaskServiceCreateRevokeResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewC1ApiTaskV1TaskServiceCreateRevokeResponse() *C1ApiTaskV1TaskServiceCreateRevokeResponse {
	this := C1ApiTaskV1TaskServiceCreateRevokeResponse{}
	return &this
}

// NewC1ApiTaskV1TaskServiceCreateRevokeResponseWithDefaults instantiates a new C1ApiTaskV1TaskServiceCreateRevokeResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewC1ApiTaskV1TaskServiceCreateRevokeResponseWithDefaults() *C1ApiTaskV1TaskServiceCreateRevokeResponse {
	this := C1ApiTaskV1TaskServiceCreateRevokeResponse{}
	return &this
}

// GetExpanded returns the Expanded field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *C1ApiTaskV1TaskServiceCreateRevokeResponse) GetExpanded() []C1ApiAppV1AppResourceServiceGetResponseExpandedInner {
	if o == nil {
		var ret []C1ApiAppV1AppResourceServiceGetResponseExpandedInner
		return ret
	}
	return o.Expanded
}

// GetExpandedOk returns a tuple with the Expanded field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *C1ApiTaskV1TaskServiceCreateRevokeResponse) GetExpandedOk() ([]C1ApiAppV1AppResourceServiceGetResponseExpandedInner, bool) {
	if o == nil || IsNil(o.Expanded) {
		return nil, false
	}
	return o.Expanded, true
}

// HasExpanded returns a boolean if a field has been set.
func (o *C1ApiTaskV1TaskServiceCreateRevokeResponse) HasExpanded() bool {
	if o != nil && IsNil(o.Expanded) {
		return true
	}

	return false
}

// SetExpanded gets a reference to the given []C1ApiAppV1AppResourceServiceGetResponseExpandedInner and assigns it to the Expanded field.
func (o *C1ApiTaskV1TaskServiceCreateRevokeResponse) SetExpanded(v []C1ApiAppV1AppResourceServiceGetResponseExpandedInner) {
	o.Expanded = v
}

// GetTaskView returns the TaskView field value if set, zero value otherwise.
func (o *C1ApiTaskV1TaskServiceCreateRevokeResponse) GetTaskView() C1ApiTaskV1TaskView {
	if o == nil || IsNil(o.TaskView) {
		var ret C1ApiTaskV1TaskView
		return ret
	}
	return *o.TaskView
}

// GetTaskViewOk returns a tuple with the TaskView field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *C1ApiTaskV1TaskServiceCreateRevokeResponse) GetTaskViewOk() (*C1ApiTaskV1TaskView, bool) {
	if o == nil || IsNil(o.TaskView) {
		return nil, false
	}
	return o.TaskView, true
}

// HasTaskView returns a boolean if a field has been set.
func (o *C1ApiTaskV1TaskServiceCreateRevokeResponse) HasTaskView() bool {
	if o != nil && !IsNil(o.TaskView) {
		return true
	}

	return false
}

// SetTaskView gets a reference to the given C1ApiTaskV1TaskView and assigns it to the TaskView field.
func (o *C1ApiTaskV1TaskServiceCreateRevokeResponse) SetTaskView(v C1ApiTaskV1TaskView) {
	o.TaskView = &v
}

func (o C1ApiTaskV1TaskServiceCreateRevokeResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o C1ApiTaskV1TaskServiceCreateRevokeResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Expanded != nil {
		toSerialize["expanded"] = o.Expanded
	}
	if !IsNil(o.TaskView) {
		toSerialize["taskView"] = o.TaskView
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *C1ApiTaskV1TaskServiceCreateRevokeResponse) UnmarshalJSON(bytes []byte) (err error) {
	varC1ApiTaskV1TaskServiceCreateRevokeResponse := _C1ApiTaskV1TaskServiceCreateRevokeResponse{}

	if err = json.Unmarshal(bytes, &varC1ApiTaskV1TaskServiceCreateRevokeResponse); err == nil {
		*o = C1ApiTaskV1TaskServiceCreateRevokeResponse(varC1ApiTaskV1TaskServiceCreateRevokeResponse)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "expanded")
		delete(additionalProperties, "taskView")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableC1ApiTaskV1TaskServiceCreateRevokeResponse struct {
	value *C1ApiTaskV1TaskServiceCreateRevokeResponse
	isSet bool
}

func (v NullableC1ApiTaskV1TaskServiceCreateRevokeResponse) Get() *C1ApiTaskV1TaskServiceCreateRevokeResponse {
	return v.value
}

func (v *NullableC1ApiTaskV1TaskServiceCreateRevokeResponse) Set(val *C1ApiTaskV1TaskServiceCreateRevokeResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableC1ApiTaskV1TaskServiceCreateRevokeResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableC1ApiTaskV1TaskServiceCreateRevokeResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableC1ApiTaskV1TaskServiceCreateRevokeResponse(val *C1ApiTaskV1TaskServiceCreateRevokeResponse) *NullableC1ApiTaskV1TaskServiceCreateRevokeResponse {
	return &NullableC1ApiTaskV1TaskServiceCreateRevokeResponse{value: val, isSet: true}
}

func (v NullableC1ApiTaskV1TaskServiceCreateRevokeResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableC1ApiTaskV1TaskServiceCreateRevokeResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


