/*
ConductorOne API

The ConductorOne API is a HTTP API for managing ConductorOne resources.

API version: 0.1.0-alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package c1api

import (
	"encoding/json"
)

// checks if the C1ApiPolicyV1ManagerApproval type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &C1ApiPolicyV1ManagerApproval{}

// C1ApiPolicyV1ManagerApproval The ManagerApproval message.
type C1ApiPolicyV1ManagerApproval struct {
	// The allowSelfApproval field.
	AllowSelfApproval *bool `json:"allowSelfApproval,omitempty"`
	// The assignedUserIds field.
	AssignedUserIds []string `json:"assignedUserIds,omitempty"`
	// The fallback field.
	Fallback *bool `json:"fallback,omitempty"`
	// The fallbackUserIds field.
	FallbackUserIds []string `json:"fallbackUserIds,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _C1ApiPolicyV1ManagerApproval C1ApiPolicyV1ManagerApproval

// NewC1ApiPolicyV1ManagerApproval instantiates a new C1ApiPolicyV1ManagerApproval object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewC1ApiPolicyV1ManagerApproval() *C1ApiPolicyV1ManagerApproval {
	this := C1ApiPolicyV1ManagerApproval{}
	return &this
}

// NewC1ApiPolicyV1ManagerApprovalWithDefaults instantiates a new C1ApiPolicyV1ManagerApproval object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewC1ApiPolicyV1ManagerApprovalWithDefaults() *C1ApiPolicyV1ManagerApproval {
	this := C1ApiPolicyV1ManagerApproval{}
	return &this
}

// GetAllowSelfApproval returns the AllowSelfApproval field value if set, zero value otherwise.
func (o *C1ApiPolicyV1ManagerApproval) GetAllowSelfApproval() bool {
	if o == nil || IsNil(o.AllowSelfApproval) {
		var ret bool
		return ret
	}
	return *o.AllowSelfApproval
}

// GetAllowSelfApprovalOk returns a tuple with the AllowSelfApproval field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *C1ApiPolicyV1ManagerApproval) GetAllowSelfApprovalOk() (*bool, bool) {
	if o == nil || IsNil(o.AllowSelfApproval) {
		return nil, false
	}
	return o.AllowSelfApproval, true
}

// HasAllowSelfApproval returns a boolean if a field has been set.
func (o *C1ApiPolicyV1ManagerApproval) HasAllowSelfApproval() bool {
	if o != nil && !IsNil(o.AllowSelfApproval) {
		return true
	}

	return false
}

// SetAllowSelfApproval gets a reference to the given bool and assigns it to the AllowSelfApproval field.
func (o *C1ApiPolicyV1ManagerApproval) SetAllowSelfApproval(v bool) {
	o.AllowSelfApproval = &v
}

// GetAssignedUserIds returns the AssignedUserIds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *C1ApiPolicyV1ManagerApproval) GetAssignedUserIds() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.AssignedUserIds
}

// GetAssignedUserIdsOk returns a tuple with the AssignedUserIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *C1ApiPolicyV1ManagerApproval) GetAssignedUserIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.AssignedUserIds) {
		return nil, false
	}
	return o.AssignedUserIds, true
}

// HasAssignedUserIds returns a boolean if a field has been set.
func (o *C1ApiPolicyV1ManagerApproval) HasAssignedUserIds() bool {
	if o != nil && IsNil(o.AssignedUserIds) {
		return true
	}

	return false
}

// SetAssignedUserIds gets a reference to the given []string and assigns it to the AssignedUserIds field.
func (o *C1ApiPolicyV1ManagerApproval) SetAssignedUserIds(v []string) {
	o.AssignedUserIds = v
}

// GetFallback returns the Fallback field value if set, zero value otherwise.
func (o *C1ApiPolicyV1ManagerApproval) GetFallback() bool {
	if o == nil || IsNil(o.Fallback) {
		var ret bool
		return ret
	}
	return *o.Fallback
}

// GetFallbackOk returns a tuple with the Fallback field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *C1ApiPolicyV1ManagerApproval) GetFallbackOk() (*bool, bool) {
	if o == nil || IsNil(o.Fallback) {
		return nil, false
	}
	return o.Fallback, true
}

// HasFallback returns a boolean if a field has been set.
func (o *C1ApiPolicyV1ManagerApproval) HasFallback() bool {
	if o != nil && !IsNil(o.Fallback) {
		return true
	}

	return false
}

// SetFallback gets a reference to the given bool and assigns it to the Fallback field.
func (o *C1ApiPolicyV1ManagerApproval) SetFallback(v bool) {
	o.Fallback = &v
}

// GetFallbackUserIds returns the FallbackUserIds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *C1ApiPolicyV1ManagerApproval) GetFallbackUserIds() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.FallbackUserIds
}

// GetFallbackUserIdsOk returns a tuple with the FallbackUserIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *C1ApiPolicyV1ManagerApproval) GetFallbackUserIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.FallbackUserIds) {
		return nil, false
	}
	return o.FallbackUserIds, true
}

// HasFallbackUserIds returns a boolean if a field has been set.
func (o *C1ApiPolicyV1ManagerApproval) HasFallbackUserIds() bool {
	if o != nil && IsNil(o.FallbackUserIds) {
		return true
	}

	return false
}

// SetFallbackUserIds gets a reference to the given []string and assigns it to the FallbackUserIds field.
func (o *C1ApiPolicyV1ManagerApproval) SetFallbackUserIds(v []string) {
	o.FallbackUserIds = v
}

func (o C1ApiPolicyV1ManagerApproval) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o C1ApiPolicyV1ManagerApproval) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AllowSelfApproval) {
		toSerialize["allowSelfApproval"] = o.AllowSelfApproval
	}
	if o.AssignedUserIds != nil {
		toSerialize["assignedUserIds"] = o.AssignedUserIds
	}
	if !IsNil(o.Fallback) {
		toSerialize["fallback"] = o.Fallback
	}
	if o.FallbackUserIds != nil {
		toSerialize["fallbackUserIds"] = o.FallbackUserIds
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *C1ApiPolicyV1ManagerApproval) UnmarshalJSON(bytes []byte) (err error) {
	varC1ApiPolicyV1ManagerApproval := _C1ApiPolicyV1ManagerApproval{}

	if err = json.Unmarshal(bytes, &varC1ApiPolicyV1ManagerApproval); err == nil {
		*o = C1ApiPolicyV1ManagerApproval(varC1ApiPolicyV1ManagerApproval)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "allowSelfApproval")
		delete(additionalProperties, "assignedUserIds")
		delete(additionalProperties, "fallback")
		delete(additionalProperties, "fallbackUserIds")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableC1ApiPolicyV1ManagerApproval struct {
	value *C1ApiPolicyV1ManagerApproval
	isSet bool
}

func (v NullableC1ApiPolicyV1ManagerApproval) Get() *C1ApiPolicyV1ManagerApproval {
	return v.value
}

func (v *NullableC1ApiPolicyV1ManagerApproval) Set(val *C1ApiPolicyV1ManagerApproval) {
	v.value = val
	v.isSet = true
}

func (v NullableC1ApiPolicyV1ManagerApproval) IsSet() bool {
	return v.isSet
}

func (v *NullableC1ApiPolicyV1ManagerApproval) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableC1ApiPolicyV1ManagerApproval(val *C1ApiPolicyV1ManagerApproval) *NullableC1ApiPolicyV1ManagerApproval {
	return &NullableC1ApiPolicyV1ManagerApproval{value: val, isSet: true}
}

func (v NullableC1ApiPolicyV1ManagerApproval) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableC1ApiPolicyV1ManagerApproval) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


