/*
ConductorOne API

The ConductorOne API is a HTTP API for managing ConductorOne resources.

API version: 0.1.0-alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package c1api

import (
	"encoding/json"
)

// checks if the C1ApiIamV1ListRolesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &C1ApiIamV1ListRolesResponse{}

// C1ApiIamV1ListRolesResponse The ListRolesResponse message.
type C1ApiIamV1ListRolesResponse struct {
	// The list field.
	List []C1ApiIamV1Role `json:"list,omitempty"`
	// The nextPageToken field.
	NextPageToken *string `json:"nextPageToken,omitempty"`
	// The notificationToken field.
	NotificationToken *string `json:"notificationToken,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _C1ApiIamV1ListRolesResponse C1ApiIamV1ListRolesResponse

// NewC1ApiIamV1ListRolesResponse instantiates a new C1ApiIamV1ListRolesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewC1ApiIamV1ListRolesResponse() *C1ApiIamV1ListRolesResponse {
	this := C1ApiIamV1ListRolesResponse{}
	return &this
}

// NewC1ApiIamV1ListRolesResponseWithDefaults instantiates a new C1ApiIamV1ListRolesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewC1ApiIamV1ListRolesResponseWithDefaults() *C1ApiIamV1ListRolesResponse {
	this := C1ApiIamV1ListRolesResponse{}
	return &this
}

// GetList returns the List field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *C1ApiIamV1ListRolesResponse) GetList() []C1ApiIamV1Role {
	if o == nil {
		var ret []C1ApiIamV1Role
		return ret
	}
	return o.List
}

// GetListOk returns a tuple with the List field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *C1ApiIamV1ListRolesResponse) GetListOk() ([]C1ApiIamV1Role, bool) {
	if o == nil || IsNil(o.List) {
		return nil, false
	}
	return o.List, true
}

// HasList returns a boolean if a field has been set.
func (o *C1ApiIamV1ListRolesResponse) HasList() bool {
	if o != nil && IsNil(o.List) {
		return true
	}

	return false
}

// SetList gets a reference to the given []C1ApiIamV1Role and assigns it to the List field.
func (o *C1ApiIamV1ListRolesResponse) SetList(v []C1ApiIamV1Role) {
	o.List = v
}

// GetNextPageToken returns the NextPageToken field value if set, zero value otherwise.
func (o *C1ApiIamV1ListRolesResponse) GetNextPageToken() string {
	if o == nil || IsNil(o.NextPageToken) {
		var ret string
		return ret
	}
	return *o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *C1ApiIamV1ListRolesResponse) GetNextPageTokenOk() (*string, bool) {
	if o == nil || IsNil(o.NextPageToken) {
		return nil, false
	}
	return o.NextPageToken, true
}

// HasNextPageToken returns a boolean if a field has been set.
func (o *C1ApiIamV1ListRolesResponse) HasNextPageToken() bool {
	if o != nil && !IsNil(o.NextPageToken) {
		return true
	}

	return false
}

// SetNextPageToken gets a reference to the given string and assigns it to the NextPageToken field.
func (o *C1ApiIamV1ListRolesResponse) SetNextPageToken(v string) {
	o.NextPageToken = &v
}

// GetNotificationToken returns the NotificationToken field value if set, zero value otherwise.
func (o *C1ApiIamV1ListRolesResponse) GetNotificationToken() string {
	if o == nil || IsNil(o.NotificationToken) {
		var ret string
		return ret
	}
	return *o.NotificationToken
}

// GetNotificationTokenOk returns a tuple with the NotificationToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *C1ApiIamV1ListRolesResponse) GetNotificationTokenOk() (*string, bool) {
	if o == nil || IsNil(o.NotificationToken) {
		return nil, false
	}
	return o.NotificationToken, true
}

// HasNotificationToken returns a boolean if a field has been set.
func (o *C1ApiIamV1ListRolesResponse) HasNotificationToken() bool {
	if o != nil && !IsNil(o.NotificationToken) {
		return true
	}

	return false
}

// SetNotificationToken gets a reference to the given string and assigns it to the NotificationToken field.
func (o *C1ApiIamV1ListRolesResponse) SetNotificationToken(v string) {
	o.NotificationToken = &v
}

func (o C1ApiIamV1ListRolesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o C1ApiIamV1ListRolesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.List != nil {
		toSerialize["list"] = o.List
	}
	if !IsNil(o.NextPageToken) {
		toSerialize["nextPageToken"] = o.NextPageToken
	}
	if !IsNil(o.NotificationToken) {
		toSerialize["notificationToken"] = o.NotificationToken
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *C1ApiIamV1ListRolesResponse) UnmarshalJSON(bytes []byte) (err error) {
	varC1ApiIamV1ListRolesResponse := _C1ApiIamV1ListRolesResponse{}

	if err = json.Unmarshal(bytes, &varC1ApiIamV1ListRolesResponse); err == nil {
		*o = C1ApiIamV1ListRolesResponse(varC1ApiIamV1ListRolesResponse)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "list")
		delete(additionalProperties, "nextPageToken")
		delete(additionalProperties, "notificationToken")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableC1ApiIamV1ListRolesResponse struct {
	value *C1ApiIamV1ListRolesResponse
	isSet bool
}

func (v NullableC1ApiIamV1ListRolesResponse) Get() *C1ApiIamV1ListRolesResponse {
	return v.value
}

func (v *NullableC1ApiIamV1ListRolesResponse) Set(val *C1ApiIamV1ListRolesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableC1ApiIamV1ListRolesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableC1ApiIamV1ListRolesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableC1ApiIamV1ListRolesResponse(val *C1ApiIamV1ListRolesResponse) *NullableC1ApiIamV1ListRolesResponse {
	return &NullableC1ApiIamV1ListRolesResponse{value: val, isSet: true}
}

func (v NullableC1ApiIamV1ListRolesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableC1ApiIamV1ListRolesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


