/*
ConductorOne API

The ConductorOne API is a HTTP API for managing ConductorOne resources.

API version: 0.1.0-alpha
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package c1api

import (
	"encoding/json"
)

// checks if the C1ApiDirectoryV1DirectoryExpandMask type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &C1ApiDirectoryV1DirectoryExpandMask{}

// C1ApiDirectoryV1DirectoryExpandMask The DirectoryExpandMask message.
type C1ApiDirectoryV1DirectoryExpandMask struct {
	// The paths field.
	Paths []string `json:"paths,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _C1ApiDirectoryV1DirectoryExpandMask C1ApiDirectoryV1DirectoryExpandMask

// NewC1ApiDirectoryV1DirectoryExpandMask instantiates a new C1ApiDirectoryV1DirectoryExpandMask object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewC1ApiDirectoryV1DirectoryExpandMask() *C1ApiDirectoryV1DirectoryExpandMask {
	this := C1ApiDirectoryV1DirectoryExpandMask{}
	return &this
}

// NewC1ApiDirectoryV1DirectoryExpandMaskWithDefaults instantiates a new C1ApiDirectoryV1DirectoryExpandMask object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewC1ApiDirectoryV1DirectoryExpandMaskWithDefaults() *C1ApiDirectoryV1DirectoryExpandMask {
	this := C1ApiDirectoryV1DirectoryExpandMask{}
	return &this
}

// GetPaths returns the Paths field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *C1ApiDirectoryV1DirectoryExpandMask) GetPaths() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Paths
}

// GetPathsOk returns a tuple with the Paths field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *C1ApiDirectoryV1DirectoryExpandMask) GetPathsOk() ([]string, bool) {
	if o == nil || IsNil(o.Paths) {
		return nil, false
	}
	return o.Paths, true
}

// HasPaths returns a boolean if a field has been set.
func (o *C1ApiDirectoryV1DirectoryExpandMask) HasPaths() bool {
	if o != nil && IsNil(o.Paths) {
		return true
	}

	return false
}

// SetPaths gets a reference to the given []string and assigns it to the Paths field.
func (o *C1ApiDirectoryV1DirectoryExpandMask) SetPaths(v []string) {
	o.Paths = v
}

func (o C1ApiDirectoryV1DirectoryExpandMask) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o C1ApiDirectoryV1DirectoryExpandMask) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Paths != nil {
		toSerialize["paths"] = o.Paths
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *C1ApiDirectoryV1DirectoryExpandMask) UnmarshalJSON(bytes []byte) (err error) {
	varC1ApiDirectoryV1DirectoryExpandMask := _C1ApiDirectoryV1DirectoryExpandMask{}

	if err = json.Unmarshal(bytes, &varC1ApiDirectoryV1DirectoryExpandMask); err == nil {
		*o = C1ApiDirectoryV1DirectoryExpandMask(varC1ApiDirectoryV1DirectoryExpandMask)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "paths")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableC1ApiDirectoryV1DirectoryExpandMask struct {
	value *C1ApiDirectoryV1DirectoryExpandMask
	isSet bool
}

func (v NullableC1ApiDirectoryV1DirectoryExpandMask) Get() *C1ApiDirectoryV1DirectoryExpandMask {
	return v.value
}

func (v *NullableC1ApiDirectoryV1DirectoryExpandMask) Set(val *C1ApiDirectoryV1DirectoryExpandMask) {
	v.value = val
	v.isSet = true
}

func (v NullableC1ApiDirectoryV1DirectoryExpandMask) IsSet() bool {
	return v.isSet
}

func (v *NullableC1ApiDirectoryV1DirectoryExpandMask) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableC1ApiDirectoryV1DirectoryExpandMask(val *C1ApiDirectoryV1DirectoryExpandMask) *NullableC1ApiDirectoryV1DirectoryExpandMask {
	return &NullableC1ApiDirectoryV1DirectoryExpandMask{value: val, isSet: true}
}

func (v NullableC1ApiDirectoryV1DirectoryExpandMask) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableC1ApiDirectoryV1DirectoryExpandMask) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


