components:
    schemas:
        c1.api.app.v1.AppEntitlement:
            description: |
                The AppEntitlement message.

                This message contains a oneof named max_grant_duration. Only a single field of the following list may be set at a time:
                  - durationUnset
                  - durationGrant
            properties:
                alias:
                    description: The alias field.
                    type: string
                appId:
                    description: The appId field.
                    type: string
                appResourceId:
                    description: The appResourceId field.
                    type: string
                appResourceTypeId:
                    description: The appResourceTypeId field.
                    type: string
                certifyPolicyId:
                    description: The certifyPolicyId field.
                    type: string
                complianceFrameworkValueIds:
                    description: The complianceFrameworkValueIds field.
                    items:
                        type: string
                    nullable: true
                    type: array
                createdAt:
                    format: date-time
                    type: string
                deletedAt:
                    format: date-time
                    type: string
                description:
                    description: The description field.
                    type: string
                displayName:
                    description: The displayName field.
                    type: string
                durationGrant:
                    format: duration
                    type: string
                durationUnset:
                    nullable: true
                    type: object
                grantCount:
                    description: The grantCount field.
                    format: int64
                    type: string
                grantPolicyId:
                    description: The grantPolicyId field.
                    type: string
                id:
                    description: The id field.
                    type: string
                provisionerPolicy:
                    $ref: '#/components/schemas/c1.api.policy.v1.ProvisionPolicy'
                revokePolicyId:
                    description: The revokePolicyId field.
                    type: string
                riskLevelValueId:
                    description: The riskLevelValueId field.
                    type: string
                slug:
                    description: The slug field.
                    type: string
                systemBuiltin:
                    description: The systemBuiltin field.
                    type: boolean
                updatedAt:
                    format: date-time
                    type: string
            type: object
        c1.api.auth.v1.IntrospectResponse:
            description: The IntrospectResponse message.
            properties:
                accessTokenId:
                    description: The accessTokenId field.
                    type: string
                features:
                    description: The features field.
                    items:
                        type: string
                    nullable: true
                    type: array
                permissions:
                    description: The permissions field.
                    items:
                        type: string
                    nullable: true
                    type: array
                principleId:
                    description: The principleId field.
                    type: string
                roles:
                    description: The roles field.
                    items:
                        type: string
                    nullable: true
                    type: array
                tenantId:
                    description: The tenantId field.
                    type: string
                userId:
                    description: The userId field.
                    type: string
            type: object
        c1.api.policy.v1.ConnectorProvision:
            description: The ConnectorProvision message.
            nullable: true
            type: object
        c1.api.policy.v1.DelegatedProvision:
            description: The DelegatedProvision message.
            nullable: true
            properties:
                appId:
                    description: The appId field.
                    type: string
                entitlementId:
                    description: The entitlementId field.
                    type: string
            type: object
        c1.api.policy.v1.ManualProvision:
            description: The ManualProvision message.
            nullable: true
            properties:
                instructions:
                    description: The instructions field.
                    type: string
                userIds:
                    description: The userIds field.
                    items:
                        type: string
                    nullable: true
                    type: array
            type: object
        c1.api.policy.v1.ProvisionPolicy:
            description: |
                The ProvisionPolicy message.

                This message contains a oneof named typ. Only a single field of the following list may be set at a time:
                  - connector
                  - manual
                  - delegated
            properties:
                connector:
                    $ref: '#/components/schemas/c1.api.policy.v1.ConnectorProvision'
                delegated:
                    $ref: '#/components/schemas/c1.api.policy.v1.DelegatedProvision'
                manual:
                    $ref: '#/components/schemas/c1.api.policy.v1.ManualProvision'
            type: object
        c1.api.requestcatalog.v2.SearchEntitlementsRequest:
            description: The SearchEntitlementsRequest message.
            properties:
                entitlementAlias:
                    description: The entitlementAlias field.
                    type: string
                pageSize:
                    description: The pageSize field.
                    format: int32
                    type: number
                pageToken:
                    description: The pageToken field.
                    type: string
                query:
                    description: The query field.
                    type: string
            type: object
        c1.api.requestcatalog.v2.SearchEntitlementsResponse:
            description: The SearchEntitlementsResponse message.
            properties:
                list:
                    description: The list field.
                    items:
                        $ref: '#/components/schemas/c1.api.app.v1.AppEntitlement'
                    nullable: true
                    type: array
                nextPageToken:
                    description: The nextPageToken field.
                    type: string
            type: object
        c1.api.user.v1.User:
            description: The User message.
            properties:
                createdAt:
                    format: date-time
                    type: string
                delegatedUserId:
                    description: The delegatedUserId field.
                    type: string
                deletedAt:
                    format: date-time
                    type: string
                department:
                    description: The department field.
                    type: string
                departmentSources:
                    description: The departmentSources field.
                    items:
                        $ref: '#/components/schemas/c1.api.user.v1.UserAttributeMappingSource'
                    nullable: true
                    type: array
                directoryIds:
                    description: The directoryIds field.
                    items:
                        type: string
                    nullable: true
                    type: array
                directoryStatus:
                    description: The directoryStatus field.
                    enum:
                        - UNKNOWN
                        - ENABLED
                        - DISABLED
                        - DELETED
                    type: string
                directoryStatusSources:
                    description: The directoryStatusSources field.
                    items:
                        $ref: '#/components/schemas/c1.api.user.v1.UserAttributeMappingSource'
                    nullable: true
                    type: array
                displayName:
                    description: The displayName field.
                    type: string
                email:
                    description: The email field.
                    type: string
                employmentStatus:
                    description: The employmentStatus field.
                    type: string
                employmentStatusSources:
                    description: The employmentStatusSources field.
                    items:
                        $ref: '#/components/schemas/c1.api.user.v1.UserAttributeMappingSource'
                    nullable: true
                    type: array
                employmentType:
                    description: The employmentType field.
                    type: string
                employmentTypeSources:
                    description: The employmentTypeSources field.
                    items:
                        $ref: '#/components/schemas/c1.api.user.v1.UserAttributeMappingSource'
                    nullable: true
                    type: array
                id:
                    description: The id field.
                    type: string
                jobTitle:
                    description: The jobTitle field.
                    type: string
                jobTitleSources:
                    description: The jobTitleSources field.
                    items:
                        $ref: '#/components/schemas/c1.api.user.v1.UserAttributeMappingSource'
                    nullable: true
                    type: array
                managerIds:
                    description: The managerIds field.
                    items:
                        type: string
                    nullable: true
                    type: array
                managerSources:
                    description: The managerSources field.
                    items:
                        $ref: '#/components/schemas/c1.api.user.v1.UserAttributeMappingSource'
                    nullable: true
                    type: array
                roleIds:
                    description: The roleIds field.
                    items:
                        type: string
                    nullable: true
                    type: array
                status:
                    description: The status field.
                    enum:
                        - UNKNOWN
                        - ENABLED
                        - DISABLED
                        - DELETED
                    type: string
                updatedAt:
                    format: date-time
                    type: string
            type: object
        c1.api.user.v1.UserAttributeMappingSource:
            description: The UserAttributeMappingSource message.
            properties:
                appId:
                    description: The appId field.
                    type: string
                appUserId:
                    description: The appUserId field.
                    type: string
                appUserProfileAttributeKey:
                    description: The appUserProfileAttributeKey field.
                    type: string
                userAttributeMappingId:
                    description: The userAttributeMappingId field.
                    type: string
                value:
                    description: The value field.
                    type: string
            type: object
        c1.api.user.v1.UserServiceGetResponse:
            description: The UserServiceGetResponse message.
            properties:
                expanded:
                    description: The expanded field.
                    items:
                        additionalProperties:
                            oneOf: []
                        description: Contains an arbitrary serialized message along with a @type that describes the type of the serialized message.
                        properties:
                            '@type':
                                description: The type of the serialized message.
                                type: string
                        type: object
                    nullable: true
                    type: array
                userView:
                    $ref: '#/components/schemas/c1.api.user.v1.UserView'
            type: object
        c1.api.user.v1.UserView:
            description: The UserView message.
            properties:
                delegatedUserPath:
                    description: The delegatedUserPath field.
                    type: string
                directoriesPath:
                    description: The directoriesPath field.
                    type: string
                managersPath:
                    description: The managersPath field.
                    type: string
                rolesPath:
                    description: The rolesPath field.
                    type: string
                user:
                    $ref: '#/components/schemas/c1.api.user.v1.User'
            type: object
info:
    description: The ConductorOne API is a HTTP API for managing ConductorOne resources.
    title: ConductorOne API
    version: 0.1.0-alpha
openapi: 3.0.3
paths:
    /api/v1/auth/introspect:
        get:
            description: Invokes the c1.api.auth.v1.Auth.Introspect method.
            operationId: c1.api.auth.v1.Auth.Introspect
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/c1.api.auth.v1.IntrospectResponse'
                    description: Succesful response
    /api/v1/entitlement/search:
        post:
            description: Invokes the c1.api.requestcatalog.v2.RequestCatalogSearchService.SearchEntitlements method.
            operationId: c1.api.requestcatalog.v2.RequestCatalogSearchService.SearchEntitlements
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/c1.api.requestcatalog.v2.SearchEntitlementsRequest'
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/c1.api.requestcatalog.v2.SearchEntitlementsResponse'
                    description: Succesful response
    /api/v1/user/get/{id}:
        get:
            description: Invokes the c1.api.user.v1.UserService.Get method.
            operationId: c1.api.user.v1.UserService.Get
            parameters:
                - in: path
                  name: id
                  required: true
                  schema:
                    description: The id field.
                    type: string
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/c1.api.user.v1.UserServiceGetResponse'
                    description: Succesful response
servers:
    - description: The ConductorOne API server for the current tenant.
      url: https://{tenantDomain}.morgabra.dev.ductone.com:2443
      variables:
        tenantDomain:
            default: invalid-example
            description: The domain of the tenant to use for this request.
